services:
  postgres:
    image: postgres:16
    container_name: locos_deporte_db
    restart: always
    environment:
      POSTGRES_DB: locos_deporte
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: locos1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: