spring.datasource.url=jdbc:postgresql://localhost:5432/locos_deporte
spring.datasource.username=postgres
spring.datasource.password=locos1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Forzamos el dialecto para que Hibernate no intente adivinarlo sin conexión
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.admin.user=AdminRoot
app.admin.password=locos1234
app.admin.email=admin@crazysports.com